graph TD;
    broadcaster --> kt
    broadcaster --> pd
    broadcaster --> xv
    broadcaster --> rg
    kt --> jv
    kt --> mt
    pd --> pr
    pd --> jp
    xv --> nd
    xv --> jm
    rg --> qs
    rg --> vq
    jv --> hj
    jv --> rc
    jv --> kt
    jv --> ln
    jv --> zp
    jv --> hf
    mt --> jv
    mt --> zp
    pr --> pd
    pr --> vx
    pr --> vn
    pr --> cl
    pr --> hm
    jp --> mx
    jp --> pr
    nd --> dg
    jm --> pb
    jm --> tm
    jm --> zx
    jm --> mk
    jm --> xv
    jm --> nd
    qs --> kf
    qs --> dr
    qs --> sc
    qs --> rg
    qs --> gl
    qs --> dx
    vq --> bs
    vq --> qs
    hj --> vc
    rc --> hj
    ln --> kj
    zp --> rc
    hf --> nm
    vx --> ns
    vn --> kj
    cl --> hm
    hm --> qb
    mx --> cl
    mx --> pr
    dg --> tm
    dg --> jm
    pb --> tp
    tm --> mh
    zx --> kj
    mk --> pb
    kf --> dx
    dr --> kj
    sc --> mv
    gl --> kf
    dx --> ts
    bs --> sc
    bs --> qs
    vc --> jv
    vc --> hf
    kj --> rx
    nm --> dh
    nm --> jv
    ns --> pr
    ns --> pn
    qb --> bf
    qb --> pr
    tp --> pf
    tp --> jm
    mh --> mk
    mh --> jm
    mv --> qs
    mv --> gl
    ts --> ng
    ts --> qs
    dh --> jv
    dh --> mc
    pn --> pr
    pn --> cb
    bf --> vx
    bf --> pr
    pf --> mf
    pf --> jm
    ng --> qs
    ng --> lh
    mc --> jv
    mc --> lv
    cb --> pr
    cb --> tk
    mf --> gv
    mf --> jm
    lh --> qs
    lh --> dl
    lv --> jv
    lv --> tg
    tk --> pr
    gv --> jm
    gv --> km
    dl --> qs
    tg --> jv
    km --> jm
