graph TD;
classDef AND fill:#f38ba8,stroke:#11111b,stroke-width:2px;
classDef OR fill:#a6e3a1,stroke:#11111b,stroke-width:2px;
classDef XOR fill:#b4befe,stroke:#11111b,stroke-width:2px;
classDef INPUT fill:#f9e2af,stroke:#11111b,stroke-width:2px;
classDef Z fill:#f2cdcd,stroke:#11111b,stroke-width:2px;
classDef VARIABLE fill:#74c7ec,stroke:#11111b,stroke-width:2px;
x00y00z00[XOR];
class x00y00z00 XOR;
x00:::INPUT;
y00:::INPUT;
z00:::Z;
x00 --> x00y00z00;
y00 --> x00y00z00;
x00y00z00 --> z00;
x00y00c00[AND];
class x00y00c00 AND;
x00:::INPUT;
y00:::INPUT;
c00:::VARIABLE;
x00 --> x00y00c00;
y00 --> x00y00c00;
x00y00c00 --> c00;
